global:
  sendAnonymousUsage: false
api:
  dashboard: true
  insecure: true
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedbydefault: false
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
log:
  level: DEBUG
  format: common
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: http
          scheme: https
  htpps:
    address: ":443"